"""
constants
"""

ACTION_SELECT = 0
ACTION_MOVE_SELECTED = 1
ACTION_RECT = 2
ACTION_ELLIPSE = 3
ACTION_ARROW = 4
ACTION_LINE = 5
ACTION_UNDO = 6
ACTION_SAVE = 7
ACTION_CANCEL = 8
ACTION_SURE = 9

DRAW_ACTION = [ACTION_RECT, ACTION_ELLIPSE, ACTION_ARROW, ACTION_LINE]

ON_THE_LEFT_SIDE = 10
ON_THE_RIGHT_SIDE = 11
ON_THE_UP_SIDE = 12
ON_THE_DOWN_SIDE = 13
ON_THE_TOP_LEFT_CORNOR = 14
ON_THE_TOP_RIGHT_CORNOR = 15
ON_THE_BOTTOM_LEFT_CORNOR = 16
ON_THE_BOTTOM_RIGHT_CORNOR = 17
INSIDE_AREA = 18
OUTSIDE_AREA = 19

# the range of judging if your mouse is on the side of selected area
ERRORRANGE = 6

PENCOLOR = '#ff0000'  #  red
PENSIZE = 1
